# Generated by Django 5.2 on 2026-04-10

import django.contrib.gis.db.models.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='BoundaryRegion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('type', models.CharField(choices=[('mine', 'mine'), ('workface', 'workface'), ('region', 'region')], default='region', max_length=20)),
                ('area', models.FloatField(default=0)),
                ('perimeter', models.FloatField(default=0)),
                ('borehole_count', models.PositiveIntegerField(default=0)),
                ('properties', models.JSONField(blank=True, default=dict)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('source', models.CharField(blank=True, default='', max_length=120)),
                ('source_crs', models.CharField(blank=True, default='', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('type', 'name'),
            },
        ),
    ]
