# Generated by Django 5.2 on 2026-04-10

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Borehole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('borehole_code', models.CharField(max_length=120, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('longitude', models.FloatField(default=0)),
                ('latitude', models.FloatField(default=0)),
                ('elevation', models.FloatField(default=0)),
                ('depth_total', models.FloatField(default=0)),
                ('workface_name', models.CharField(blank=True, default='', max_length=120)),
                ('remark', models.TextField(blank=True, default='')),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='BoreholeLayer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('layer_name', models.CharField(max_length=120)),
                ('top_depth', models.FloatField(default=0)),
                ('thickness', models.FloatField(default=0)),
                ('bottom_depth', models.FloatField(default=0)),
                ('color', models.CharField(default='#23d18b', max_length=20)),
                ('sort_order', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('borehole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layers', to='boreholes.borehole')),
            ],
            options={
                'ordering': ('sort_order', 'created_at'),
            },
        ),
        migrations.AddConstraint(
            model_name='boreholelayer',
            constraint=models.UniqueConstraint(fields=('borehole', 'sort_order'), name='uniq_borehole_layer_sort_order'),
        ),
    ]
