# Generated by Django 5.2 on 2026-04-10

import django.contrib.gis.db.models.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='RasterLayer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('type', models.CharField(default='subsidence', max_length=80)),
                ('url', models.CharField(blank=True, default='', max_length=255)),
                ('opacity', models.FloatField(default=0.62)),
                ('legend_config', models.JSONField(blank=True, default=list)),
                ('description', models.TextField(blank=True, default='')),
                ('time_tag', models.CharField(blank=True, default='', max_length=120)),
                ('source_crs', models.CharField(blank=True, default='', max_length=120)),
                ('bounds', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
                ('west', models.FloatField(default=0)),
                ('south', models.FloatField(default=0)),
                ('east', models.FloatField(default=0)),
                ('north', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
